# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ImageFadein' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ImageFadein

  target 'ImageFadeinTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ImageFadeinUITests' do
    inherit! :search_paths
    # Pods for testing
  end
pod 'SDWebImage', '~> 5.0.0-beta3'

end
